version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: cv-rewriter-postgres
    environment:
      POSTGRES_DB: cvdb
      POSTGRES_USER: cv_user
      POSTGRES_PASSWORD: cv_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cv_user -d cvdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
